message: teste leitura

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

agent:
   rabbit:
      user: guest
      pwd: guest
      host: localhost
      port: 15672

service:
   brpa-controller: BRPA-CONTROLLER


spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 'root'
        platform: mysql
        url: jdbc:mysql://localhost/brpa_controller?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        show-sql: true
